### ISSUE TITLE
Kaltura Attachment Dialog and Edit Dialog styles are broken

### ISSUE THREAD

**Issue by SammyIsConfused** [openequella/openEQUELLA-Kaltura#8]
**Describe the bug**
In the new UI, the Kaltura Attachment and Edit attachment dialogs in contribution wizards have broken styles and need some EBP (legacy.scss) work.

**To Reproduce**

1. In the New UI, open a contribution in a collection that contains a Kaltura attachment control.
2. Click on the control.
3. Note that the control is styled poorly. 
4. Search for, select and save a Kaltura attachment to this control.
5. Click "Edit" next to the Kaltura attachment.
6. Not that this dialog is also broken.

**Expected behavior**
Similar to other "EBP" work done in the openEQUELLA repo, this dialog should present in a usable format.

**Screenshots**
![image](https://user-images.githubusercontent.com/24543345/103628865-b0354500-4f93-11eb-8a71-a3c8c5fc4e66.png)
![image](https://user-images.githubusercontent.com/24543345/103628906-bfb48e00-4f93-11eb-922c-b1120d8b1c5e.png)
![image](https://user-images.githubusercontent.com/24543345/103628973-d4912180-4f93-11eb-9a89-603d5b1f7f38.png)

**Platform:**

- OpenEquella Version: 2020.2
- OS: Ubuntu 20.04.1 LTS
- Browser: Firefox

**Comment by snehanaik22** [comment]
Tested.
