### ISSUE TITLE
Uploading content to Kaltura from openEQUELLA doesn't work

### ISSUE THREAD

**Issue by SammyIsConfused** [openequella/openEQUELLA-Kaltura#9]
**Describe the bug**
When using a Kaltura attachment control from openEQUELLA, if you click "Upload new Kaltura Media" nothing happens. This happens both in the new UI and the old UI.

**To Reproduce**

1. Open a contribution to a collection that contains a Kaltura attachment control.
2. Click on the attachment control to open the dialog.
3. Click "Upload new Kaltura Media"
4. Note that nothing happens.

**Expected behavior**
That the uploader dialog opens and the user is able to upload into Kaltura.

**Screenshots**
New UI:

https://user-images.githubusercontent.com/24543345/103629868-fb9c2300-4f94-11eb-9929-44b8c41cead8.mp4

Old UI:

https://user-images.githubusercontent.com/24543345/103629990-24bcb380-4f95-11eb-9f0c-c1eac28d8275.mp4

**Platform:**

- OpenEquella Version: 2020.2
- OS: Ubuntu 20.04.1 LTS
- Browser: Firefox

**Additional context**

This happens because the integration in it's current state calls into the legacy API for Kaltura. The uploader widget that gets pulled down is a SWF file, which is no longer runnable in a browser. In order for this functionality to work we need to determine the newer way to achieve this task and re-implement the feature to work with the new API.

**Comment by snehanaik22** [comment]
Tested.
